### ISSUE TITLE
Can you add the A100 gpus?

### ISSUE THREAD

**Issue by oneonlee** [RahulSChand/gpu_poor#13]
Can you add the A100 gpus?

The A100 GPUs are available with 40GB and 80GB of VRAM.

Thanks for the good website.

**Comment by ChloeL19** [comment]
This would be sooo useful, thanks!

**Comment by hunter-xue** [comment]
A100 and H100 and other datacenter GPU type should be very useful.

**Comment by RahulSChand** [comment]
Added A100 & H100 gpus.
