### ISSUE TITLE
DeepSpeed support

### ISSUE THREAD

**Issue by LaniakeaS** [RahulSChand/gpu_poor#6]
if i'm using deepspeed+huggingface (including ZeRO-1, 2, 3). Is there any difference on memory usage compare with just using 🤗? If there is a difference, is it gonna be supported?

**Comment by RahulSChand** [comment]
There is no difference. The default assumption in the app is that the user is using some library like Deepspeed or FSDP (https://pytorch.org/blog/introducing-pytorch-fully-sharded-data-parallel-api/) for training on multi-GPUs.
